GET http://localhost:8080/car

###

DELETE http://localhost:8080/car/1
###

POST http://localhost:8080/car
Content-Type: application/json

{
  "carBrand": "Toyota",
  "carModel": "Camry",
  "releaseYear": "b",
  "condition": "New",
  "price": 30000
}
###

